package entities;
// Generated May 8, 2017 4:30:20 PM by Hibernate Tools 4.3.1



/**
 * Activity generated by hbm2java
 */
public class Activity  implements java.io.Serializable {


     private Integer id;
     private String activityName;
     private String description;
     private Integer point;
     private String subjectId;

    public Activity() {
    }

    public Activity(String activityName, String description, Integer point, String subjectId) {
       this.activityName = activityName;
       this.description = description;
       this.point = point;
       this.subjectId = subjectId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getActivityName() {
        return this.activityName;
    }
    
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getPoint() {
        return this.point;
    }
    
    public void setPoint(Integer point) {
        this.point = point;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }




}


