package entities;
// Generated May 8, 2017 4:30:20 PM by Hibernate Tools 4.3.1



/**
 * ListInClass generated by hbm2java
 */
public class ListInClass  implements java.io.Serializable {


     private Integer id;
     private String studentId;
     private String subjectId;

    public ListInClass() {
    }

    public ListInClass(String studentId, String subjectId) {
       this.studentId = studentId;
       this.subjectId = subjectId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }




}


