package entities;
// Generated May 8, 2017 4:30:20 PM by Hibernate Tools 4.3.1



/**
 * ReportActivity generated by hbm2java
 */
public class ReportActivity  implements java.io.Serializable {


     private Integer id;
     private String studentId;
     private Integer point;
     private String subjectId;
     private Integer activityId;
     private String state;

    public ReportActivity() {
    }

    public ReportActivity(String studentId, Integer point, String subjectId, Integer activityId, String state) {
       this.studentId = studentId;
       this.point = point;
       this.subjectId = subjectId;
       this.activityId = activityId;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public Integer getPoint() {
        return this.point;
    }
    
    public void setPoint(Integer point) {
        this.point = point;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


