package entities;
// Generated May 8, 2017 4:30:20 PM by Hibernate Tools 4.3.1



/**
 * ReportAttendance generated by hbm2java
 */
public class ReportAttendance  implements java.io.Serializable {


     private Integer id;
     private String otherSpecify;
     private String studentId;
     private String subjectId;
     private String state;
     private String date;
     private String time;

    public ReportAttendance() {
    }

    public ReportAttendance(String otherSpecify, String studentId, String subjectId, String state, String date, String time) {
       this.otherSpecify = otherSpecify;
       this.studentId = studentId;
       this.subjectId = subjectId;
       this.state = state;
       this.date = date;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOtherSpecify() {
        return this.otherSpecify;
    }
    
    public void setOtherSpecify(String otherSpecify) {
        this.otherSpecify = otherSpecify;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


