package entities;
// Generated May 8, 2017 4:30:20 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String studentId;
     private String name;
     private String surname;
     private String major;
     private String level;

    public Student() {
    }

	
    public Student(String studentId) {
        this.studentId = studentId;
    }
    public Student(String studentId, String name, String surname, String major, String level) {
       this.studentId = studentId;
       this.name = name;
       this.surname = surname;
       this.major = major;
       this.level = level;
    }
   
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }




}


