package entities;
// Generated May 8, 2017 4:30:20 PM by Hibernate Tools 4.3.1



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private String subjectId;
     private String subjectName;
     private String teacherId;

    public Subject() {
    }

	
    public Subject(String subjectId) {
        this.subjectId = subjectId;
    }
    public Subject(String subjectId, String subjectName, String teacherId) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.teacherId = teacherId;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }




}


